ログイン機能をMVCに分割
kaori23/cafeSearchApp pull request #8
Opened 2020-08-23 11:23 UTC by kaori23

【質問の概要】
非同期処理が完了した後、非同期処理の結果によって実行したい処理を変える方法の実装方法

現在ログイン機能を以下のメソッドを用いて実装しております。

1. ログインボタンをクリック時以下のメソッドを実行する
 1-1 validateFieldsメソッド：IDとpasswordに適切が値が入力されているかをチェック
 1-2 loginUserメソッド：firebaseのログイン機能を用いてログインを試みる(非同期処理)
 1-3 getUserInfoメソッド： loginUserメソッドで取得したログインユーザのID(uid)を元にfirebaseのDBから登録ずみのログインユーザ名を取得(非同期処理)
 1-4 トップ画面に遷移する

上記をMVCモデルに当てはめると、下記の通りになると思い、ファイルを分けました。
Modelファイル: 1-2 ,1-3が該当(DBとのやりとりなど内部的な処理が含まれており隠蔽化が必要だと思うから)
Controllerファイル: 1-1,1-4が該当(画面遷移などviewを操作する処理はControllerから行うべきだから)

ファイルは分けますが、処理は上から順に行いたいと思っています。
しかし、現在の実装では1-4の処理が1-3の処理を待たずに実行されています。どうすれば1-3の非同期処理の完了を待ってから1-4の処理を実行できるかが知りたいです。

【前提となる情報】
このプルリクエスト内に上記処理の具体的なコードについてコメントを入れています。

【期待する挙動】
非同期処理の結果を待ってから画面遷移するか否か(1-3までの処理が問題なく行われた場合のみ画面遷移としたい)の条件分岐ができ流ようにしたいです。

【発生したエラーや意図しない挙動の説明】

エラーについて：
別件かもしれませんが、画面遷移するメソッドに関してビルドすると以下のエラー文が出ます。
「Use of undeclared type 'TopMapViewController'」
このエラー文が出ていてもシミュレーションは動いているという状況です。

意図しない挙動の説明：
1-3までの非同期処理を待たずに画面遷移してしまうこと。
1-2、1-3は非同期処理で1-4は同期処理なのでこうなってしまう事の意味はわかっているのですが、1-3までの非同期処理を待ってから画面遷移させる方法が分からないです。
ファイルが異なるため、ネストするのも難しいのではないかと思っております。(1-1から1-4までを一つのファイルで実装する場合は一度問題なく実装しています。コミットログ：commit 3c101ce087fab313cf4d11ad3efd70f1423d785a)

【デバッグ内容と自身の考察】
上記【発生したエラーや意図しない挙動の説明】に記載した通りです。

【求める回答】
非同期処理が完了した後、非同期処理の結果によって実行したい処理を変える方法の実装方法、発生しているエラー解決についてアドバイスしていただきたいです。

【そもそもの概念やよく分かっていないこと】
クロージャーやPromiseなどについての理解が浅いです。
今回の質問について、一度クロージャーやPromiseでどうにかできないか考えたのですがどう実装していいか分かりませんでした。。。

2020-08-24 01:16 UTC, yamatakuType commented
うん！とてもいい質問ですね！
同期処理と非同期処理の取り扱いは難しいですよね😌

> 上記をMVCモデルに当てはめると、下記の通りになると思い、ファイルを分けました。

ファイルの分け方はこの方針で問題ありません👍

> 非同期処理の結果を待ってから画面遷移するか否か(1-3までの処理が問題なく行われた場合のみ画面遷移としたい)の条件分岐ができ流ようにしたいです。

これは「①DispatchGroupで並行処理させるパターン」と「②Delegateパターン」の2つが考えられます。

それぞれの参考記事を記載しますね💁‍♂️

① https://qiita.com/shtnkgm/items/d9b78365a12b08d5bde1

② https://qiita.com/kichiemon/items/a55b3624e042ea843573

個人的にはDelegateパターンの方が非同期処理以外でも応用できて汎用性が高いので、ここで習得しておくのがオススメです💡

> このエラー文が出ていてもシミュレーションは動いているという状況です。

これは恐らくXcodeのキャッシュが残っていて正常にコンパイルされていないことが原因かもしれないですね🤔
Xcodeのキャッシュをクリアすると改善しませんか？

2020-08-28 01:19 UTC, yamataku29 requested changes
具体的な内容を見る前に一点修正依頼です。
「File changed」が3953ファイル(差分が100万行弱)になっている事がわかると思いますが、通常レビュー依頼をするPRにおいてここまで大規模な変更が加わっているものをレビュー依頼することはほぼありません。(このボリュームで出しても範囲が広すぎてレビュアーがレビューすることが困難だからですね)

通常は大体差分が数十行-1000行程度に留めるのが一般的です。

なぜこれが起きているかというと、　CocoaPodsで管理しているライブラリのソースコードを全てコミットしているからですね。

通常、CocoaPodsはPodfile.lockというファイルにバージョンなどの記載があるため、個別のPCにおいてこの Podfile.lockがあれば同一の環境構築が可能です。(この辺りは少しCocoaPodsの仕様を調べても良いかもしおれません)

そのため、Pods/配下のディレクトリは本来Githubの差分監視対象に含める必要は無いのですね💁‍♂️
(※一部例外などもありますが、今回は説明を割愛)

なので、まずは具体的なレビューをする前に、CocoaPodsで管理しているライブラリのソースコードをGithubの差分監視対象から除外しましょう💡

2020-08-28 02:09 UTC, kaori23 commented
ご確認ありがとうございます。
Podsフォルダ下をリモート から削除しましたので再度ご確認いただけますでしょうか

2020-08-28 10:56 UTC, yamataku29 reviewed
いくつかコメント入れましたが、概ね問題無さそうです🙆‍♂️💡

2020-08-28 10:56 UTC, yamataku29 commented on cafeSearchApp/AccountDelegate.swift
> +    func onFailureLogin(errorMessagge: String) -> Void
ここは戻り値無しでも問題ないですね💁‍♂️

2020-08-28 10:56 UTC, yamataku29 commented on cafeSearchApp/Constants.swift
> +    }
ここはenumを用いてもいいかもしれません👏

```swift
enum Storyboard: String {
    case signupComplete
    case topMap
}
// Storyboard.signupComplete.rawValue
```

2020-08-28 12:54 UTC, merged